### PR TITLE
Upgrade to terraform 0.12.12

### PR DESCRIPTION
**Pull request by ltomes**
Upgrade to terraform 0.12.12

I run into state errors using latest terraform with blast radius, so I updated the tf version.

It appears circleci is not happy with the configuration change I provided. I don't think there is anything I can do to resolve that issue though, @28mm will have to clear the docker cache I believe to resolve that.

### CODE REVIEW

**Review by MacFlurry — COMMENTED** [review]
please upgrade to `TF_VERSION=0.12.24`

**Comment by ltomes** [comment]
I can update this pr tonight.

**Comment by MacFlurry** [comment]
Hi @ltomes 

Have you had time to update this PR?
Sincerely,
MacFlurry

**Comment by ltomes** [comment]
Hi there, sorry for the delay.
I put out a new pr here: https://github.com/28mm/blast-radius/pull/77

**Pull request merged**
